# Generated by Django 3.0.6 on 2020-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballparks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballpark',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ballpark',
            name='league',
        ),
        migrations.RemoveField(
            model_name='ballpark',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ballpark',
            name='name',
        ),
        migrations.AddField(
            model_name='ballpark',
            name='users',
            field=models.ManyToManyField(related_name='ballparks', to='ballparks.User'),
        ),
        migrations.AddField(
            model_name='ballpark',
            name='visited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
