# Generated by Django 2.2 on 2020-05-28 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballparks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballpark',
            name='user',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, related_name='ballparks', to='ballparks.User'),
            preserve_default=False,
        ),
    ]
