# Generated by Django 3.0.6 on 2020-05-31 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ballparks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballpark',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
