# Generated by Django 3.0.6 on 2020-05-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballparks', '0002_auto_20200528_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballpark',
            name='users',
        ),
        migrations.AddField(
            model_name='ballpark',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='ballparks', to='ballparks.User'),
            preserve_default=False,
        ),
    ]
