# Generated by Django 3.0.6 on 2020-05-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballparks', '0002_ballpark_visited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballpark',
            name='visited_at',
            field=models.DateField(),
        ),
    ]
