# Generated by Django 3.0.6 on 2020-05-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballparks', '0003_auto_20200531_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballpark',
            name='visited_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
