# Generated by Django 2.2 on 2020-05-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballparks', '0003_auto_20200528_1930'),
        ('ballparks', '0002_ballpark_user'),
    ]

    operations = [
    ]
